### ISSUE TITLE
Fix text variables grids not showing in regression

### ISSUE THREAD

**Issue by felipe-olmos-orange** [khiopsrelease/kv-release#104] opened 2023-04-05 07:54 UTC
KViz Version: 10.2.14

When visualizing the regression results for a task with Text variables the regression grid is not shown in the lower-right pane. Instead it shows _No data_ (attached the example .khj file).

[000_000_10000words_AllReports.zip](https://github.com/khiopsrelease/kv-release/files/11156397/000_000_10000words_AllReports.zip)

![image](https://user-images.githubusercontent.com/92923444/230017098-477310e2-7a11-4606-9baa-97c80e147a46.png)

**Comment by khiopsrelease** [comment] 2023-05-24 14:06
duplicate of #106 
fixed in 11.0.0

**Closed** 2023-05-24 14:07 UTC
